FROM python:3.10-slim
WORKDIR /app
COPY ./dashboard /app
RUN apt-get update && apt-get install -y libpq-dev && \
    pip install --no-cache-dir streamlit pandas psycopg2-binary
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.enableCORS=false"]
