FROM python:3.10-slim

WORKDIR /app

# Install system deps for psycopg2 and build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir streamlit pandas psycopg2-binary

# Copy your dashboard code
COPY ./dashboard /app/dashboard

WORKDIR /app/dashboard

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
